import type { Locale, ReasonCode } from './types'

// Localized labels for scan reason codes. The codes themselves are the stable keys; this map turns
// them into human strings per locale. 'unknown' covers a null/absent code. Shared by the web portal
// (rendered in the active user locale) and the worker's notifications (rendered in the configured
// notification locale) — neither needs a full i18n runtime, just this pure lookup.
// The 'en' values are canonical and must stay in sync with the vocabulary in types.ts.
// Technical tokens (npm, nvm, pnpm, PATH, JSON, Node, bash, Yarn, npm 6) are intentionally not translated.

type ReasonKey = ReasonCode | 'unknown'

export const REASON_CODE_LABELS: Record<Locale, Record<ReasonKey, string>> = {
    'en': {
        unknown: 'unknown',
        ok: 'OK',
        no_lockfile: 'No lockfile',
        unknown_pm: 'Unknown package manager',
        yarn_v1_unsupported: 'Yarn 1.x unsupported',
        pm_missing: 'Package manager not on PATH',
        nvm_missing: 'nvm not on PATH',
        node_below_min: 'Node below minimum',
        npm_below_min: 'npm below minimum',
        pnpm_below_min: 'pnpm below minimum',
        audit_spawn_error: 'Audit spawn error',
        audit_parse_error: 'Audit JSON parse error',
        audit_schema_mismatch: 'Audit JSON schema mismatch',
        audit_empty_output: 'Audit produced no output',
        audit_no_advisories: 'Audit output had no advisories',
        legacy_npm6_format: 'Legacy npm 6 format',
        nvm_node_missing: 'nvm: Node version not installed',
        nvm_install_failed: 'nvm: Node version install failed',
        bash_missing: 'bash not on PATH',
        audit_unknown_failure: 'Audit failed (unknown)',
        osv_db_not_seeded: 'OSV database not downloaded yet',
        osv_db_unavailable: 'OSV database unavailable',
        timeout: 'Timeout'
    },
    'es': {
        unknown: 'desconocido',
        ok: 'OK',
        no_lockfile: 'Sin lockfile',
        unknown_pm: 'Gestor de paquetes desconocido',
        yarn_v1_unsupported: 'Yarn 1.x no compatible',
        pm_missing: 'Gestor de paquetes no está en PATH',
        nvm_missing: 'nvm no está en PATH',
        node_below_min: 'Node por debajo del mínimo',
        npm_below_min: 'npm por debajo del mínimo',
        pnpm_below_min: 'pnpm por debajo del mínimo',
        audit_spawn_error: 'Error al iniciar audit',
        audit_parse_error: 'Error al analizar el JSON de audit',
        audit_schema_mismatch: 'Esquema JSON de audit no coincide',
        audit_empty_output: 'audit no produjo salida',
        audit_no_advisories: 'La salida de audit no tenía avisos',
        legacy_npm6_format: 'Formato heredado de npm 6',
        nvm_node_missing: 'nvm: versión de Node no instalada',
        nvm_install_failed: 'nvm: falló la instalación de la versión de Node',
        bash_missing: 'bash no está en PATH',
        audit_unknown_failure: 'audit falló (desconocido)',
        osv_db_not_seeded: 'Base de datos OSV aún no descargada',
        osv_db_unavailable: 'Base de datos OSV no disponible',
        timeout: 'Tiempo de espera agotado'
    },
    'fr': {
        unknown: 'inconnu',
        ok: 'OK',
        no_lockfile: 'Aucun lockfile',
        unknown_pm: 'Gestionnaire de paquets inconnu',
        yarn_v1_unsupported: 'Yarn 1.x non pris en charge',
        pm_missing: 'Gestionnaire de paquets absent du PATH',
        nvm_missing: 'nvm absent du PATH',
        node_below_min: 'Node en dessous du minimum',
        npm_below_min: 'npm en dessous du minimum',
        pnpm_below_min: 'pnpm en dessous du minimum',
        audit_spawn_error: 'Erreur de lancement d’audit',
        audit_parse_error: 'Erreur d’analyse du JSON d’audit',
        audit_schema_mismatch: 'Schéma JSON d’audit non conforme',
        audit_empty_output: 'audit n’a produit aucune sortie',
        audit_no_advisories: 'La sortie d’audit ne contenait aucun avis',
        legacy_npm6_format: 'Ancien format npm 6',
        nvm_node_missing: 'nvm : version de Node non installée',
        nvm_install_failed: 'nvm : échec de l’installation de la version de Node',
        bash_missing: 'bash absent du PATH',
        audit_unknown_failure: 'Échec d’audit (inconnu)',
        osv_db_not_seeded: 'Base de données OSV pas encore téléchargée',
        osv_db_unavailable: 'Base de données OSV indisponible',
        timeout: 'Délai dépassé'
    },
    'de': {
        unknown: 'unbekannt',
        ok: 'OK',
        no_lockfile: 'Keine Lockfile',
        unknown_pm: 'Unbekannter Paketmanager',
        yarn_v1_unsupported: 'Yarn 1.x nicht unterstützt',
        pm_missing: 'Paketmanager nicht im PATH',
        nvm_missing: 'nvm nicht im PATH',
        node_below_min: 'Node unter Minimum',
        npm_below_min: 'npm unter Minimum',
        pnpm_below_min: 'pnpm unter Minimum',
        audit_spawn_error: 'Fehler beim Starten von audit',
        audit_parse_error: 'Fehler beim Parsen des audit-JSON',
        audit_schema_mismatch: 'audit-JSON-Schema stimmt nicht überein',
        audit_empty_output: 'audit lieferte keine Ausgabe',
        audit_no_advisories: 'audit-Ausgabe enthielt keine Hinweise',
        legacy_npm6_format: 'Veraltetes npm-6-Format',
        nvm_node_missing: 'nvm: Node-Version nicht installiert',
        nvm_install_failed: 'nvm: Installation der Node-Version fehlgeschlagen',
        bash_missing: 'bash nicht im PATH',
        audit_unknown_failure: 'audit fehlgeschlagen (unbekannt)',
        osv_db_not_seeded: 'OSV-Datenbank noch nicht heruntergeladen',
        osv_db_unavailable: 'OSV-Datenbank nicht verfügbar',
        timeout: 'Zeitüberschreitung'
    },
    'pt-BR': {
        unknown: 'desconhecido',
        ok: 'OK',
        no_lockfile: 'Sem lockfile',
        unknown_pm: 'Gerenciador de pacotes desconhecido',
        yarn_v1_unsupported: 'Yarn 1.x não suportado',
        pm_missing: 'Gerenciador de pacotes fora do PATH',
        nvm_missing: 'nvm fora do PATH',
        node_below_min: 'Node abaixo do mínimo',
        npm_below_min: 'npm abaixo do mínimo',
        pnpm_below_min: 'pnpm abaixo do mínimo',
        audit_spawn_error: 'Erro ao iniciar o audit',
        audit_parse_error: 'Erro ao analisar o JSON do audit',
        audit_schema_mismatch: 'Esquema JSON do audit incompatível',
        audit_empty_output: 'audit não gerou saída',
        audit_no_advisories: 'A saída do audit não tinha avisos',
        legacy_npm6_format: 'Formato antigo do npm 6',
        nvm_node_missing: 'nvm: versão do Node não instalada',
        nvm_install_failed: 'nvm: falha ao instalar a versão do Node',
        bash_missing: 'bash fora do PATH',
        audit_unknown_failure: 'Falha no audit (desconhecida)',
        osv_db_not_seeded: 'Banco de dados OSV ainda não baixado',
        osv_db_unavailable: 'Banco de dados OSV indisponível',
        timeout: 'Tempo esgotado'
    },
    'it': {
        unknown: 'sconosciuto',
        ok: 'OK',
        no_lockfile: 'Nessun lockfile',
        unknown_pm: 'Gestore di pacchetti sconosciuto',
        yarn_v1_unsupported: 'Yarn 1.x non supportato',
        pm_missing: 'Gestore di pacchetti non nel PATH',
        nvm_missing: 'nvm non nel PATH',
        node_below_min: 'Node sotto il minimo',
        npm_below_min: 'npm sotto il minimo',
        pnpm_below_min: 'pnpm sotto il minimo',
        audit_spawn_error: 'Errore di avvio di audit',
        audit_parse_error: 'Errore di analisi del JSON di audit',
        audit_schema_mismatch: 'Schema JSON di audit non corrispondente',
        audit_empty_output: 'audit non ha prodotto output',
        audit_no_advisories: 'L’output di audit non conteneva avvisi',
        legacy_npm6_format: 'Vecchio formato npm 6',
        nvm_node_missing: 'nvm: versione di Node non installata',
        nvm_install_failed: 'nvm: installazione della versione di Node non riuscita',
        bash_missing: 'bash non nel PATH',
        audit_unknown_failure: 'audit non riuscito (sconosciuto)',
        osv_db_not_seeded: 'Database OSV non ancora scaricato',
        osv_db_unavailable: 'Database OSV non disponibile',
        timeout: 'Timeout scaduto'
    },
    'ja': {
        unknown: '不明',
        ok: 'OK',
        no_lockfile: 'ロックファイルがありません',
        unknown_pm: '不明なパッケージマネージャー',
        yarn_v1_unsupported: 'Yarn 1.x は未対応',
        pm_missing: 'パッケージマネージャーが PATH にありません',
        nvm_missing: 'nvm が PATH にありません',
        node_below_min: 'Node が最小バージョン未満',
        npm_below_min: 'npm が最小バージョン未満',
        pnpm_below_min: 'pnpm が最小バージョン未満',
        audit_spawn_error: 'audit の起動エラー',
        audit_parse_error: 'audit の JSON 解析エラー',
        audit_schema_mismatch: 'audit の JSON スキーマ不一致',
        audit_empty_output: 'audit が出力を生成しませんでした',
        audit_no_advisories: 'audit の出力にアドバイザリがありませんでした',
        legacy_npm6_format: '旧 npm 6 形式',
        nvm_node_missing: 'nvm: Node バージョンが未インストール',
        nvm_install_failed: 'nvm: Node バージョンのインストールに失敗',
        bash_missing: 'bash が PATH にありません',
        audit_unknown_failure: 'audit が失敗しました（不明）',
        osv_db_not_seeded: 'OSV データベースは未ダウンロード',
        osv_db_unavailable: 'OSV データベースを利用できません',
        timeout: 'タイムアウト'
    },
    'zh-CN': {
        unknown: '未知',
        ok: 'OK',
        no_lockfile: '无锁文件',
        unknown_pm: '未知的包管理器',
        yarn_v1_unsupported: '不支持 Yarn 1.x',
        pm_missing: '包管理器不在 PATH 中',
        nvm_missing: 'nvm 不在 PATH 中',
        node_below_min: 'Node 低于最低版本',
        npm_below_min: 'npm 低于最低版本',
        pnpm_below_min: 'pnpm 低于最低版本',
        audit_spawn_error: 'audit 启动错误',
        audit_parse_error: 'audit JSON 解析错误',
        audit_schema_mismatch: 'audit JSON 架构不匹配',
        audit_empty_output: 'audit 未产生输出',
        audit_no_advisories: 'audit 输出中没有公告',
        legacy_npm6_format: '旧版 npm 6 格式',
        nvm_node_missing: 'nvm：未安装 Node 版本',
        nvm_install_failed: 'nvm：Node 版本安装失败',
        bash_missing: 'bash 不在 PATH 中',
        audit_unknown_failure: 'audit 失败（未知）',
        osv_db_not_seeded: 'OSV 数据库尚未下载',
        osv_db_unavailable: 'OSV 数据库不可用',
        timeout: '超时'
    },
    'ko': {
        unknown: '알 수 없음',
        ok: 'OK',
        no_lockfile: '잠금 파일 없음',
        unknown_pm: '알 수 없는 패키지 매니저',
        yarn_v1_unsupported: 'Yarn 1.x 미지원',
        pm_missing: '패키지 매니저가 PATH에 없음',
        nvm_missing: 'nvm이 PATH에 없음',
        node_below_min: 'Node가 최소 버전 미만',
        npm_below_min: 'npm이 최소 버전 미만',
        pnpm_below_min: 'pnpm이 최소 버전 미만',
        audit_spawn_error: 'audit 실행 오류',
        audit_parse_error: 'audit JSON 구문 분석 오류',
        audit_schema_mismatch: 'audit JSON 스키마 불일치',
        audit_empty_output: 'audit가 출력을 생성하지 않음',
        audit_no_advisories: 'audit 출력에 권고가 없음',
        legacy_npm6_format: '구형 npm 6 형식',
        nvm_node_missing: 'nvm: Node 버전이 설치되지 않음',
        nvm_install_failed: 'nvm: Node 버전 설치 실패',
        bash_missing: 'bash가 PATH에 없음',
        audit_unknown_failure: 'audit 실패 (알 수 없음)',
        osv_db_not_seeded: 'OSV 데이터베이스가 아직 다운로드되지 않음',
        osv_db_unavailable: 'OSV 데이터베이스를 사용할 수 없음',
        timeout: '시간 초과'
    },
    'ru': {
        unknown: 'неизвестно',
        ok: 'OK',
        no_lockfile: 'Нет lockfile',
        unknown_pm: 'Неизвестный менеджер пакетов',
        yarn_v1_unsupported: 'Yarn 1.x не поддерживается',
        pm_missing: 'Менеджер пакетов не в PATH',
        nvm_missing: 'nvm не в PATH',
        node_below_min: 'Node ниже минимума',
        npm_below_min: 'npm ниже минимума',
        pnpm_below_min: 'pnpm ниже минимума',
        audit_spawn_error: 'Ошибка запуска audit',
        audit_parse_error: 'Ошибка разбора JSON от audit',
        audit_schema_mismatch: 'Несоответствие схемы JSON audit',
        audit_empty_output: 'audit не выдал результата',
        audit_no_advisories: 'В выводе audit нет рекомендаций',
        legacy_npm6_format: 'Устаревший формат npm 6',
        nvm_node_missing: 'nvm: версия Node не установлена',
        nvm_install_failed: 'nvm: не удалось установить версию Node',
        bash_missing: 'bash не в PATH',
        audit_unknown_failure: 'Сбой audit (неизвестно)',
        osv_db_not_seeded: 'База данных OSV ещё не загружена',
        osv_db_unavailable: 'База данных OSV недоступна',
        timeout: 'Тайм-аут'
    }
}

export function reasonCodeLabel(code: ReasonCode | null, locale: Locale = 'en'): string {
    const key: ReasonKey = code || 'unknown'
    const table = REASON_CODE_LABELS[locale] || REASON_CODE_LABELS['en']
    return table[key] || REASON_CODE_LABELS['en'][key] || key
}
