import { describe, expect, it } from 'vitest'
import { parseArrayOfTables } from './toml-lite'

// Scoped to exactly one TOML shape: `[[package]]` arrays-of-tables with scalar and single-line-array
// values, which is all Cargo.lock / poetry.lock / uv.lock use. The tests below therefore pin the
// supported subset AND the deliberate non-support, so a future "it doesn't handle nested tables" bug
// report can be answered from here.

const CARGO = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "anyhow"
version = "1.0.86"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "b3d1d046238990b9cf5bcde22a3fb3584ee5cf65fb2765f454ed428c7a0063da"

[[package]]
name = "clap"
version = "4.5.4"
dependencies = [
 "clap_builder",
 "clap_derive",
]

[[package]]
name = "libc"
version = "0.2.155"
`

describe('parseArrayOfTables', function () {
    it('extracts one entry per array header', function () {
        const tables = parseArrayOfTables(CARGO, 'package')
        expect(tables.map(function name(t) { return t.name })).toEqual(['anyhow', 'clap', 'libc'])
    })

    it('strips quotes from scalar values', function () {
        const tables = parseArrayOfTables(CARGO, 'package')
        expect(tables[0]?.version).toBe('1.0.86')
        expect(tables[0]?.source).toBe('registry+https://github.com/rust-lang/crates.io-index')
    })

    it('ignores keys outside any array-of-tables entry', function () {
        const tables = parseArrayOfTables(CARGO, 'package')
        expect(tables.some(function hasVersionThree(t) { return t.version === '3' })).toBe(false)
    })

    it('returns an empty list when the table name never appears', function () {
        expect(parseArrayOfTables(CARGO, 'metadata')).toEqual([])
    })

    it('returns an empty list for empty input', function () {
        expect(parseArrayOfTables('', 'package')).toEqual([])
    })

    // A documented limitation, pinned so it stays deliberate: the reader is line-oriented, so a
    // multi-line `dependencies = [` block yields an EMPTY list and its continuation lines are skipped.
    // Nothing downstream reads Cargo dependency edges today; if that changes, this test is the tripwire.
    it('yields an empty list for a multi-line array', function () {
        const tables = parseArrayOfTables(CARGO, 'package')
        expect(tables[1]?.dependencies).toEqual([])
    })

    it('reads a single-line array as a string list', function () {
        const tables = parseArrayOfTables('[[package]]\ndeps = ["a", "b", "c"]\n', 'package')
        expect(tables[0]?.deps).toEqual(['a', 'b', 'c'])
    })

    it('reads an empty single-line array as an empty list', function () {
        const tables = parseArrayOfTables('[[package]]\ndeps = []\n', 'package')
        expect(tables[0]?.deps).toEqual([])
    })

    it('strips a trailing comment', function () {
        const tables = parseArrayOfTables('[[package]]\nname = "serde" # the good one\n', 'package')
        expect(tables[0]?.name).toBe('serde')
    })

    // A `#` inside a quoted value is data, not a comment — hence the quote-aware scanner.
    it('keeps a hash that is inside a quoted string', function () {
        const tables = parseArrayOfTables('[[package]]\nsource = "git+https://x/y#abc"\n', 'package')
        expect(tables[0]?.source).toBe('git+https://x/y#abc')
    })

    it('drops a whole-line comment', function () {
        const tables = parseArrayOfTables('[[package]]\n# a note\nname = "serde"\n', 'package')
        expect(tables[0]).toEqual({ name: 'serde' })
    })

    // A nested header such as [package.dependencies] closes the current entry, so its keys are not
    // folded into the parent — which is what keeps poetry.lock's sub-tables from polluting the package.
    it('closes the current entry at a nested table header', function () {
        const text = '[[package]]\nname = "a"\n\n[package.dependencies]\nfoo = "1.0"\n'
        expect(parseArrayOfTables(text, 'package')).toEqual([{ name: 'a' }])
    })

    it('closes the current entry at a different array header', function () {
        const text = '[[package]]\nname = "a"\n\n[[other]]\nname = "b"\n'
        expect(parseArrayOfTables(text, 'package')).toEqual([{ name: 'a' }])
    })

    it('handles CRLF line endings', function () {
        expect(parseArrayOfTables('[[package]]\r\nname = "a"\r\n', 'package')).toEqual([{ name: 'a' }])
    })

    it('accepts single-quoted values', function () {
        expect(parseArrayOfTables("[[package]]\nname = 'a'\n", 'package')).toEqual([{ name: 'a' }])
    })

    it('leaves a bare unquoted value as-is', function () {
        expect(parseArrayOfTables('[[package]]\noptional = true\n', 'package')).toEqual([{ optional: 'true' }])
    })

    it('ignores a line with no assignment', function () {
        expect(parseArrayOfTables('[[package]]\nname = "a"\ngarbage\n', 'package')).toEqual([{ name: 'a' }])
    })

    it('ignores an assignment with an empty key', function () {
        expect(parseArrayOfTables('[[package]]\n = "a"\nname = "b"\n', 'package')).toEqual([{ name: 'b' }])
    })

    it('keeps the last value when a key repeats', function () {
        expect(parseArrayOfTables('[[package]]\nname = "a"\nname = "b"\n', 'package')).toEqual([{ name: 'b' }])
    })

    it('produces an empty entry for a header with no keys', function () {
        expect(parseArrayOfTables('[[package]]\n', 'package')).toEqual([{}])
    })
})
